#!/usr/bin/env perl
package Universa::datastore;

use warnings;
use strict;

use FindBin qw($Bin);
use lib "$Bin/lib";
use Universa::FORTH;
use Universa::FORTH::Plugin::DataStore;
use Devel::Confess;
use Die::Hard;

my %heap = ();


for(;;) {
my $hardened  = Universa::FORTH->new; # Interpreter stored elsewhere
#my $hardened = Die::Hard->new($session);
$hardened->add_plugin(Universa::FORTH::Plugin::DataStore->new(Heap => \%heap));
$hardened->repl;
}

exit;
