#!/usr/bin/env perl

use warnings;
use strict;

use FindBin qw($Bin);
use lib "$Bin/lib";

use Universa::DataStore;


my $datastore = Universa::DataStore->new;
$datastore->start_server(
    LocalPort => 9003,
    LocalAddr => 'localhost',
    ReuseAddr => 1,
    Listen    => 20,
    Blocking  => 1,
    );

1;
